spring:
  application:
    name: usian-content-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.160.136:7001
        - 192.168.160.136:7002
        - 192.168.160.136:7003
        - 192.168.160.136:7004
        - 192.168.160.136:7005
        - 192.168.160.136:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
ribbon:
  eureka:
    enabled: true

#大广告位图片信息
AD_CATEGORY_ID: 89
AD_HEIGHT: 240
AD_WIDTH: 670
AD_HEIGHTB: 240
AD_WIDTHB: 550

#配置缓存首页大广告位的 key
PORTAL_AD_KEY: PORTAL_AD_KEY