server:
  port: 8202
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: usian-order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 192.168.160.128
    username: admin
    password: 1111
    virtual-host: /
  redis:
    cluster:
      nodes:
        - 192.168.160.136:7001
        - 192.168.160.136:7002
        - 192.168.160.136:7003
        - 192.168.160.136:7004
        - 192.168.160.136:7005
        - 192.168.160.136:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
#订单
ORDER_ID_KEY: ORDER_ID_KEY
ORDER_ID_BEGIN: 100544
ORDER_ITEM_ID_KEY: ORDER_ITEM_ID_KEY